
-- Create Params Table
CREATE TABLE IF NOT EXISTS Params (
    id INT AUTO_INCREMENT PRIMARY KEY,
    `key` VARCHAR(255) UNIQUE NOT NULL,
    `value` VARCHAR(255) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO Params (`key`, `value`) VALUES
('MONEY_MAX', '1000'),
('MONEY_INIT', '100'),
('SHOP_INITAL_POWER_COST', '20'),
('SHOP_LATEGAME_POWER_COST', '10'),
('SHOP_POWER_DECK_INFLATION_LIMIT', '4'),
('CLIENT_1_INITAL_HAND', '1,2,3,4,5'),
('CLIENT_2_INITAL_HAND', 'P,2,3,4,5'),
('INTIIAL_DECK_SIZE', '6')
ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
